#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tvheadend"
name = "Tvheadend"
description.en = "TV streaming server and recorder"
description.fr = "Serveur de streaming et d'enregistrement TV"

version = "4.3.2009~ynh10"

maintainers = ["Sylvain Cecchetto"]

[upstream]
license = "GPL-3.0"
website = "https://tvheadend.org"
userdoc = "https://tvheadend.org/projects/tvheadend/wiki"
code = "https://github.com/tvheadend/tvheadend"

[integration]
yunohost = ">= 4.3.0"
architectures = ["amd64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tvh"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.superuser]
    ask.en = "Choose the superuser name in order to login on Tvheadend"
    ask.fr = "Choisissez le nom du superutilisateur pour la connexion à Tvheadend"
    type = "string"
    example = "johndoe"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main_buster]
    amd64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/buster/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~buster/tvheadend_4.3-2192~gc9b38a81a~buster_amd64.deb"
    amd64.sha256 = "faf486839aa96058b20bd14242cde15371072d69b92313f9a60c63fa21bfc27a"
    armhf.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/buster/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~buster/tvheadend_4.3-2192~gc9b38a81a~buster_armhf.deb"
    armhf.sha256 = "8c5e16b2320f3de4bd145bdd4de8cd5be6298b3b61412c943435c756b1c508d2"
    arm64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/buster/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~buster/tvheadend_4.3-2192~gc9b38a81a~buster_arm64.deb"
    arm64.sha256 = "8e5464ab7d5634942fe5da7d68a773b1dcd09b4736c4994a2065705b556e25dc"
    rename = "tvheadend.deb"

    format = "whatever"
    extract = false
    prefetch = false
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "tarball"

    [resources.sources.main_bullseye]
    amd64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bullseye/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~bullseye/tvheadend_4.3-2192~gc9b38a81a~bullseye_amd64.deb"
    amd64.sha256 = "e8f027620c5af52a805809ff6b42ee321db775f92fb161a6e5875f936f577782"
    armhf.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bullseye/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~bullseye/tvheadend_4.3-2192~gc9b38a81a~bullseye_armhf.deb"
    armhf.sha256 = "2b34f372c6272e47880555dd67a1aba23b0410d4b69d5aee41483829bcb3ef89"
    arm64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bullseye/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~bullseye/tvheadend_4.3-2192~gc9b38a81a~bullseye_arm64.deb"
    arm64.sha256 = "f672912eb67fe3ac9d469c55d87ce2dde097d441413c862eef758e49b140c5a8"
    rename = "tvheadend.deb"

    format = "whatever"
    extract = false
    prefetch = false
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9981
    stream.default = 9982
    stream.exposed = "TCP"

    [resources.apt]
    packages = [
        "libavahi-client3",
        "libavahi-common3",
        "libc6",
        "libdbus-1-3",
        "libdvbcsa1",
        "libpcre3",
        "libssl1.1",
        "libstdc++6",
        "liburiparser1",
        "zlib1g",
        "bzip2",
    ]
