#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tvheadend"
name = "Tvheadend"
description.en = "TV streaming server and recorder"
description.fr = "Serveur de streaming et d'enregistrement TV"

version = "4.3.2009~ynh11"

maintainers = ["Sylvain Cecchetto"]

[upstream]
license = "GPL-3.0"
website = "https://tvheadend.org"
userdoc = "https://tvheadend.org/projects/tvheadend/wiki"
code = "https://github.com/tvheadend/tvheadend"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tvh"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.superuser]
    ask.en = "Choose the superuser name in order to login on Tvheadend"
    ask.fr = "Choisissez le nom du superutilisateur pour la connexion à Tvheadend"
    type = "string"
    example = "johndoe"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main_bullseye]
    amd64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bullseye/main/t/tv/tvheadend_4.3-2316~g4874aaa31~bullseye/tvheadend_4.3-2316~g4874aaa31~bullseye_amd64.deb"
    amd64.sha256 = "68df32013182284d37d069c8d9f74d9208918d5a34184bfe848d8804b4226be7"
    arm64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bullseye/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~bullseye/tvheadend_4.3-2192~gc9b38a81a~bullseye_arm64.deb"
    arm64.sha256 = "f672912eb67fe3ac9d469c55d87ce2dde097d441413c862eef758e49b140c5a8"
    armhf.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bullseye/main/t/tv/tvheadend_4.3-2192~gc9b38a81a~bullseye/tvheadend_4.3-2192~gc9b38a81a~bullseye_armhf.deb"
    armhf.sha256 = "2b34f372c6272e47880555dd67a1aba23b0410d4b69d5aee41483829bcb3ef89"
    rename = "tvheadend.deb"

    format = "whatever"
    extract = false
    prefetch = false
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset.amd64 = "tarball"
    autoupdate.asset.arm64 = "tarball"
    autoupdate.asset.armhf = "tarball"

    [resources.sources.main_bookworm]
    amd64.url = "https://dl.cloudsmith.io/public/tvheadend/tvheadend/deb/debian/pool/bookworm/main/t/tv/tvheadend_4.3-2316~g4874aaa31~bookworm/tvheadend_4.3-2316~g4874aaa31~bookworm_amd64.deb"
    amd64.sha256 = "3f5cfc7b7405cece814e37a16a98ac919ad8c5f071ae1c5ceb38c6a904adeb66"
    rename = "tvheadend.deb"

    format = "whatever"
    extract = false
    prefetch = false
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    dir = "/var/lib/tvheadend"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 9981
    stream.default = 9982
    stream.exposed = "TCP"
