#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    args.superuser = "package_checker"

    # test_upgrade_from.e82643952e5567db826790e1e4a353559f66f112.name = "4.3.1979~ynh9"

    [default.curl_tests]
    main.logged_on_sso = true
