#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
superuser=$(ynh_app_setting_get --app=$app --key=superuser)
password=$(ynh_app_setting_get --app=$app --key=password)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
port=$(ynh_app_setting_get --app=$app --key=port)
stream_port=$(ynh_app_setting_get --app=$app --key=stream_port)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# STOP TVHEADEND SERVICE
#=================================================
ynh_script_progression --message="Stopping $app service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app.log"

#=================================================
# BACKUP THE APP MAIN DIR AND CONFIG FILES
#=================================================
ynh_script_progression --message="Backing up $app main directory and config files..." --weight=4

ynh_backup --src_path="/etc/default/tvheadend"
ynh_backup --src_path="$final_path"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Backing up nginx web server configuration..." --weight=1

ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE AND LOG FILE
#=================================================
ynh_script_progression --message="Backing up logrotate configuration and log file..." --weight=1

ynh_backup --src_path="/etc/logrotate.d/$app"
ynh_backup --src_path="/var/log/$app.log"

#=================================================
# START TVHEADEND SERVICE
#=================================================
ynh_script_progression --message="Starting $app service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)." --last


