#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# Update Tvheadend configuration file
if [ "$change_path" -eq 1 ]; then
    # Update Tvheadend configuration file
    ynh_script_progression "Updating Tvheadend configuration..."
    if [ "$path" = "/" ]; then
        ynh_config_add --template="tvheadend_no_subpath" --destination="/etc/default/tvheadend"
    else
        ynh_config_add --template="tvheadend" --destination="/etc/default/tvheadend"
    fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
