#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
superuser=$YNH_APP_ARG_SUPERUSER
password=$YNH_APP_ARG_PASSWORD

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=2

final_path=/home/hts # Default path for Tvheadend deb package
test ! -e "$final_path" || ynh_die --message="The path $final_path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=2

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url
ynh_app_setting_set --app=$app --key=superuser --value=$superuser
ynh_app_setting_set --app=$app --key=password --value=$password
ynh_app_setting_set --app=$app --key=final_path --value=$final_path

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN PORTS
#=================================================
ynh_script_progression --message="Configuring firewall..." --weight=15

# Find a free port for the web server
port=$(ynh_find_port --port=9981)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $port
ynh_app_setting_set --app=$app --key=port --value=$port

# Find a free port for the streaming server
stream_port=$(ynh_find_port --port=9982)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $stream_port
ynh_app_setting_set --app=$app --key=stream_port --value=$stream_port

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=15

if [ -n "$(uname -m | grep arm)" ]
then
    ynh_install_app_dependencies $pkg_dependencies_rb
else
	ynh_install_app_dependencies $pkg_dependencies_x86
fi

#=================================================
# DOWNLOAD TVHEADEND DEB PACKAGE
#=================================================
ynh_script_progression --message="Downloading Tvheadend..." --weight=5

temp_folder="$(mktemp -d)"
tvheadend_deb_dst="$temp_folder/tvheadend_deb.deb"
tvheadend_deb_url=""

if [ -n "$(uname -m | grep arm)" ]
then
    tvheadend_deb_url="$tvheadend_deb_arm"
elif [ -n "$(uname -m | grep x86_64)" ]
then
    tvheadend_deb_url="$tvheadend_deb_x86_64"
else
	tvheadend_deb_url="$tvheadend_deb_x86_32"
fi

ynh_exec_quiet "wget -q -O $tvheadend_deb_dst $tvheadend_deb_url"

#=================================================
# INSTALL TVHEADEND DEB PACKAGE
#=================================================
ynh_script_progression --message="Installing Tvheadend..." --weight=24

ynh_exec_warn_less dpkg -i $tvheadend_deb_dst

ynh_secure_remove --file="$temp_folder"

# The deb install automatically create the hts system user

# Tvheadend automatically start after install
# we stop it before the configuration
ynh_systemd_action --service_name=$app --action="stop"

#=================================================
# MODIFY TVHEADEND CONFIG FILES
#=================================================
# Copy and modify /etc/default/tvheadend
cp ../conf/tvheadend /etc/default/tvheadend
ynh_replace_string --match_string="__CONF_DIR__" --replace_string="$final_path/.hts/tvheadend" --target_file="/etc/default/tvheadend"
ynh_replace_string --match_string="__PORT__" --replace_string="$port" --target_file="/etc/default/tvheadend"
ynh_replace_string --match_string="__PATH__" --replace_string="$path_url" --target_file="/etc/default/tvheadend"
ynh_replace_string --match_string="__STREAM_PORT__" --replace_string="$stream_port" --target_file="/etc/default/tvheadend"
ynh_replace_string --match_string="__APP__" --replace_string="$app" --target_file="/etc/default/tvheadend"
ynh_store_file_checksum --file="/etc/default/tvheadend"

# Copy and modify /home/hts/.hts/tvheadend/superuser
cp ../conf/superuser $final_path/.hts/tvheadend/superuser
ynh_replace_string --match_string="__SUPERUSER__" --replace_string="$superuser" --target_file="$final_path/.hts/tvheadend/superuser"
ynh_replace_string --match_string="__PASSWORD__" --replace_string="$password" --target_file="$final_path/.hts/tvheadend/superuser"
ynh_store_file_checksum --file="$final_path/.hts/tvheadend/superuser"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

# Use logrotate to manage application logfile(s)
touch /var/log/$app.log
chmod 666 /var/log/$app.log
ynh_use_logrotate --logfile=/var/log/$app.log

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================
yunohost service add $app --log "/var/log/$app.log"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring SSOwat..." --weight=1

ynh_app_setting_set --app=$app --key=skipped_uris --value="/"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# PREVENT TVHEADEND BEING UPGRADED THROUGHT APT
#=================================================
ynh_script_progression --message="Prevent Tvheadend being upgraded throught APT..." --weight=1

apt-mark hold tvheadend

#=================================================
# START TVHEADEND SERVICE
#=================================================
ynh_script_progression --message="Starting Tvheadend service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of Tvheadend completed, HTTP port is $port and HTSP port is $stream_port" --last
