#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
superuser=$(ynh_app_setting_get --app=$app --key=superuser)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
port=$(ynh_app_setting_get --app=$app --key=port)
stream_port=$(ynh_app_setting_get --app=$app --key=stream_port)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================
# Remove a service from the admin panel, added by `yunohost service add`
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
    ynh_script_progression --message="Removing $app service..." --weight=1
    yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE TVHEADEND SERVICE
#=================================================
ynh_script_progression --message="Stopping $app service..." --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE TVHEADEND
#=================================================
ynh_script_progression --message="Removing $app..." --weight=5

ynh_package_autopurge $app

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=3

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing $app main directory..." --weight=1

# Remove the app directory securely (/home/hts folder)
ynh_secure_remove --file="$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing nginx web server configuration..." --weight=1

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# CLOSE TVHEADEND PORTS
#=================================================
if yunohost firewall list | grep -q "\- $port$"
then
    ynh_script_progression --message="Closing port $port..." --weight=4
    ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

if yunohost firewall list | grep -q "\- $stream_port$"
then
    ynh_script_progression --message="Closing port $stream_port..." --weight=4
    ynh_exec_warn_less yunohost firewall disallow TCP $stream_port
fi


#=================================================
# SPECIFIC REMOVE
#=================================================
ynh_script_progression --message="Removing $app log file..." --weight=1

# Remove the log files
ynh_secure_remove --file="/var/log/$app.log"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated hts system user..." --weight=1

# Delete a system user
ynh_system_user_delete --username=hts

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Removal of $app completed" --time --last

