#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
superuser=$(ynh_app_setting_get --app=$app --key=superuser)
password=$(ynh_app_setting_get --app=$app --key=password)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
port=$(ynh_app_setting_get --app=$app --key=port)
stream_port=$(ynh_app_setting_get --app=$app --key=stream_port)

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND DISABLE TVHEADEND SERVICE
#=================================================
ynh_script_progression --message="Stopping Tvheadend service..." --weight=2

ynh_systemd_action --service_name=$app --action=stop
ynh_exec_quiet systemctl disable $app --quiet
ynh_exec_quiet systemctl daemon-reload

#=================================================
# UNHOLD TVHEADEND FROM APT
#=================================================
ynh_script_progression --message="Disable prevent Tvheadend being upgraded throught APT..." --weight=2

apt-mark unhold tvheadend

#=================================================
# REMOVE TVHEADEND
#=================================================
ynh_script_progression --message="Removing Tvheadend..." --weight=6

ynh_package_autopurge $app

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove $app
fi

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

ynh_script_progression --message="Removing $app log file..." --weight=1

# Remove the log files
ynh_secure_remove --file="/var/log/$app.log"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=3

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR AND CONFIG FILES
#=================================================
ynh_script_progression --message="Removing Tvheadend main directory and config files..." --weight=2

# Remove the app directory securely (/home/hts folder)
ynh_secure_remove --file="$final_path"
ynh_secure_remove --file="/etc/default/tvheadend"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# CLOSE PORTS
#=================================================
if yunohost firewall list | grep -q "\- $port$"
then
    ynh_script_progression --message="Closing port $port..." --weight=8
    ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

if yunohost firewall list | grep -q "\- $stream_port$"
then
    ynh_script_progression --message="Closing port $stream_port..." --weight=8
    ynh_exec_warn_less yunohost firewall disallow TCP $stream_port
fi

#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated hts system user..." --weight=1

# Delete a system user
ynh_system_user_delete --username=hts

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Removal of Tvheadend completed" --last
